echo "###########################################################################################################"
echo "#                                   Restore Apps from TWRP Backup                                         #"
echo "#                                                                                                         #"
echo "# This is a bash script that automates the process of manually restoring android apps from a TWRP backup. #"
echo "###########################################################################################################"
echo "##                           Don't TWRP backups have a restore process?                                  ##"
echo "###########################################################################################################"
echo "#            Well, yes. A TWRP data restore reflashes all your andorid app data /data/data.               #"	
echo "#            However, if you just completely wiped your phone during a ROM upgrade or change              #"
echo "#                You may not want to/ be able to restore all your applications.                           #"
echo "#                This script allows you to automate the manual restore process                            #"
echo "#                 So you can be selective about what applications you restore.                            #"
echo "###########################################################################################################"
echo "##                                      How does it work?                                                 #"
echo "###########################################################################################################"
echo "#                                1. Extract data.ext4 volumes                                             #"
echo "#                                2. Connects to phone via adb                                             #"
echo "#                                3. Install app on phone                                                  #"
echo "#                                4. Pushes TWRP app data backup to android app data location              #"
echo "#                                5. Gets the userId for the app                                           #"
echo "#                                6. Changes ownership of app data folders to application via the userId   #"
echo "#                                7. Restore the SELinux attributes of the folder                          #"
echo "###########################################################################################################"
